import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,checkGuide,bestPick,bestWeapon,get panelKind(){return panel&&panel.kind}}")
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        pick="__T.G.inv.find(s=>s&&s.id==='pickWood')"
        r=await ev(pg,f"()=>{pick}.dur")
        rec('내구도','시작 나무 곡괭이 내구도 200', r==200, r)
        async def setup(extra=''):
            await ev(pg,"()=>{const G=__T.G;for(let y=106;y<116;y++)for(let x=104;x<118;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=2}G.enemies.length=0;G.fish=null;G.p.x=110.5;G.p.y=110.5;G.p.face={x:1,y:0};G.sel=5;"+extra+"}")
            await pg.wait_for_timeout(150)
        await setup("G.wall[__T.idx(111,110)]=1;")
        await hold(pg,1500)
        r=await ev(pg,f"()=>[__T.G.wall[__T.idx(111,110)], {pick}.dur]")
        rec('내구도','흙벽 캐면 캔 횟수만큼 닳음 (흙벽 3번)', r==[0,197], str(r))
        await setup(f"{pick}.dur=1;G.wall[__T.idx(111,110)]=1;")
        await tap(pg,1)
        r=await ev(pg,f"()=>[{pick}.dur, __T.bestPick().id, document.querySelector('#toasts').innerText.includes('나무 곡괭이가 망가졌어요')]")
        rec('내구도','0이 되면 망가짐 + 알림, 맨손으로 전환', r==[0,'hand',True], str(r))
        await tap(pg,1); r=await ev(pg,f"()=>[{pick}.dur, !!__T.G.inv.find(s=>s&&s.id==='pickWood')]")
        rec('내구도','망가져도 사라지지 않고 맨손으로 계속 캐짐', r==[0,True], str(r))
        r=await ev(pg,"()=>{const i=__T.G.inv.findIndex(s=>s&&s.id==='pickWood');__T.openPanel('inv');const el=document.querySelector(`#sheet .slot[data-i=\"${i}\"]`);const c=el.className;__T.closePanel();return c}")
        rec('표시','망가진 도구 칸 표시', 'broken' in r, r)
        # sword wears only on hit
        sw="__T.G.inv.find(s=>s&&s.id==='swordWood')"
        await setup()
        d0=await ev(pg,f"()=>{sw}.dur"); await tap(pg,2,400); d1=await ev(pg,f"()=>{sw}.dur")
        rec('내구도','허공에 휘두르면 안 닳음', d0==d1, f'{d0} {d1}')
        await ev(pg,"()=>{const G=__T.G;G.enemies.push({k:'slimeG',x:111.2,y:110.5,hp:999,vx:0,vy:0,t:0,hurt:0,kx:0,ky:0,z:0,air:0,land:0,cd:9,anim:0})}")
        await pg.wait_for_timeout(100); await tap(pg,1); d2=await ev(pg,f"()=>{sw}.dur")
        rec('내구도','적을 맞히면 1 닳음', d2==d1-1, f'{d1} {d2}')
        # rod broken
        await setup(f"__T.addItem('rod',1);__T.G.inv.find(s=>s&&s.id==='rod').dur=0;G.floor[__T.idx(111,110)]=__T.WATER;")
        r=await ev(pg,"()=>[__T.decide().k,__T.decide().lbl]")
        rec('내구도','망가진 낚싯대 → 낚시 불가 안내', r==['info','낚싯대 고장'], str(r))
        # chest keeps durability
        await setup("const o={t:'chest',items:Array(18).fill(null)};G.objs.set(__T.idx(111,110),o);")
        r=await ev(pg,"""()=>{const G=__T.G,i=G.inv.findIndex(s=>s&&s.id==='swordWood');G.inv[i].dur=37;__T.openPanel('chest',{i:__T.idx(111,110)});return i}""")
        await pg.wait_for_timeout(500)
        await pg.click(f'#sheet [data-a=cin][data-i="{r}"]'); await pg.wait_for_timeout(200)
        await pg.click('#sheet [data-a=cout][data-i="0"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,f"()=>{sw}.dur"); await ev(pg,"()=>__T.closePanel()")
        rec('내구도','상자에 넣었다 빼도 내구도 유지', r==37, r)
        # repair
        await setup("G.objs.set(__T.idx(111,111),{t:'bench'});__T.addItem('wood',10);")
        await ev(pg,"()=>{__T.openPanel('craft',{st:'bench'})}"); await pg.wait_for_timeout(500)
        await pg.click('#sheet [data-a=tab][data-i=fix]'); await pg.wait_for_timeout(300)
        txt=await ev(pg,"()=>document.querySelector('#sheet .sh-body').innerText")
        rec('수리','수리 탭에 닳은 도구 목록', '나무 곡괭이' in txt and '망가짐' in txt and '나무 검' in txt, txt[:120].replace('\n',' / '))
        w0=await ev(pg,"()=>__T.countItem('wood')")
        pi=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='pickWood')")
        await pg.click(f'#sheet [data-a=fix][data-i="{pi}"]'); await pg.wait_for_timeout(300)
        r=await ev(pg,f"()=>[{pick}.dur, __T.countItem('wood')]")
        rec('수리','망가진 곡괭이 수리: 나무 3개 → 내구도 200', r==[200,w0-3], f'{r} (wood before {w0})')
        r=await ev(pg,"()=>{const s=__T.G.inv.find(s=>s&&s.id==='swordWood');return [s.dur, document.querySelector('#sheet .sh-body').innerText.includes('나무 1/1')||document.querySelector('#sheet .sh-body').innerText.includes('/2')]}")
        rec('수리','덜 닳은 도구는 재료가 적게 듦', r[1], str(r))
        await pg.screenshot(path=SP+'qa10_fix.png')
        await ev(pg,"()=>__T.closePanel()")
        # away from bench
        await setup("__T.G.inv.find(s=>s&&s.id==='pickWood').dur=5;")
        await ev(pg,"()=>{__T.openPanel('craft',{st:'bench'})}"); await pg.wait_for_timeout(500); await pg.click('#sheet [data-a=tab][data-i=fix]'); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>[document.querySelector('#sheet .sh-body').innerText.includes('작업대 근처에서'), [...document.querySelectorAll('#sheet [data-a=fix]')].every(b=>b.disabled)]")
        rec('수리','작업대 없으면 수리 불가 안내', r==[True,True], str(r)); await ev(pg,"()=>__T.closePanel()")
        # save
        r=await ev(pg,"()=>{const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);const a=__T.G.inv.find(x=>x&&x.id==='pickWood').dur;s.inv.forEach(x=>{if(x)delete x.dur});__T.deserialize(s);const b=__T.G.inv.find(x=>x&&x.id==='pickWood');return [a,b.dur==null, __T.bestPick().id]}")
        rec('저장','내구도 저장 / 예전 세이브는 새것 취급', r==[5,True,'pickWood'], str(r))
        # shovel broken
        await setup("__T.addItem('shovel',1);__T.G.inv.find(s=>s&&s.id==='shovel').dur=0;G.sel=G.inv.findIndex(s=>s&&s.id==='shovel');G.floor[__T.idx(111,110)]=5;")
        r=await ev(pg,"()=>__T.decide().lbl")
        rec('내구도','망가진 삽 → 안내', r=='삽 고장', r)
        await ev(pg,"()=>{const G=__T.G;G.inv.find(s=>s&&s.id==='shovel').dur=250}"); await tap(pg,1)
        r=await ev(pg,"()=>__T.G.inv.find(s=>s&&s.id==='shovel').dur")
        rec('내구도','삽으로 걷으면 1 닳음', r==249, r)
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
