import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
async def main():
    mkpage(SRC,'qa.html')
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        await ev(pg,"()=>{const G=__T.G;G.inv.fill(null);['pickCopper','swordCopper','shovel','rod','pickWood','swordCrystal'].forEach(k=>__T.addItem(k,1));G.inv.find(s=>s&&s.id==='swordCopper').dur=0;G.objs.set(__T.idx(Math.floor(G.p.x)+1,Math.floor(G.p.y)),{t:'bench'})}")
        await ev(pg,"()=>__T.openPanel('craft',{st:'bench'})"); await pg.wait_for_timeout(500)
        await pg.click('#sheet [data-a=tab][data-i=salv]'); await pg.wait_for_timeout(300)
        txt=await ev(pg,"()=>document.querySelector('#sheet .sh-body').innerText.replace(/\\n/g,' / ')")
        rec('분해','분해 탭에 장비 6개 + 돌려받을 재료 표시', await ev(pg,"()=>document.querySelectorAll('#sheet [data-a=salv]').length")==6 and '구리괴 +3' in txt and '나무 +1' in txt, txt[:160])
        await pg.screenshot(path=SP+'qa11_salv.png')
        ci=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='pickCopper')")
        await pg.click(f'#sheet [data-a=salv][data-i="{ci}"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,f"()=>[document.querySelector('#sheet [data-a=salv][data-i=\"{ci}\"]').textContent, !!__T.G.inv[{ci}]]")
        rec('분해','한 번 누르면 확인(정말?), 아직 안 사라짐', r==['정말?',True], str(r))
        await pg.click(f'#sheet [data-a=salv][data-i="{ci}"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.countItem('pickCopper')>0, __T.countItem('copperBar'), __T.countItem('wood')]")
        rec('분해','구리 곡괭이(구리괴 4·나무 2) → 구리괴 3·나무 1', r==[False,3,1], str(r))
        si=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='swordCopper')")
        await pg.click(f'#sheet [data-a=salv][data-i="{si}"]'); await pg.click(f'#sheet [data-a=salv][data-i="{si}"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.countItem('copperBar'), __T.countItem('wood'), document.querySelector('#toasts').innerText.includes('구리 검을 분해했어요')]")
        rec('분해','망가진 구리 검(구리괴 5·나무 1)도 분해 → 구리괴 +4·나무 +1', r==[7,2,True], str(r))
        ri=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='swordCrystal')")
        await pg.click(f'#sheet [data-a=salv][data-i="{ri}"]'); await pg.click(f'#sheet [data-a=salv][data-i="{ri}"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.countItem('crystal'), __T.countItem('ironBar')]")
        rec('분해','수정 검(수정 8·철괴 3) → 수정 6·철괴 2', r==[6,2], str(r))
        wi=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='pickWood')")
        await pg.click(f'#sheet [data-a=salv][data-i="{wi}"]'); await pg.click(f'#sheet [data-a=salv][data-i="{wi}"]'); await pg.wait_for_timeout(200)
        rec('분해','시작 나무 곡괭이 → 나무 2', await ev(pg,"()=>__T.countItem('wood')")==4)
        # tab change cancels confirm
        oi=await ev(pg,"()=>__T.G.inv.findIndex(s=>s&&s.id==='rod')")
        await pg.click(f'#sheet [data-a=salv][data-i="{oi}"]'); await pg.click('#sheet [data-a=tab][data-i=fix]'); await pg.click('#sheet [data-a=tab][data-i=salv]'); await pg.wait_for_timeout(200)
        r=await ev(pg,f"()=>document.querySelector('#sheet [data-a=salv][data-i=\"{oi}\"]').textContent")
        rec('분해','탭을 바꾸면 확인 취소', r=='분해', r)
        await ev(pg,"()=>__T.closePanel()")
        # away from bench
        await ev(pg,"()=>{const G=__T.G;G.p.x=60.5;G.p.y=60.5}"); await pg.wait_for_timeout(100)
        await ev(pg,"()=>__T.openPanel('craft',{st:'bench'})"); await pg.wait_for_timeout(500); await pg.click('#sheet [data-a=tab][data-i=salv]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[document.querySelector('#sheet .sh-body').innerText.includes('작업대 근처에서'), [...document.querySelectorAll('#sheet [data-a=salv]')].every(b=>b.disabled)]")
        rec('분해','작업대 없으면 분해 불가', r==[True,True], str(r))
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
