import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,RECIPES}")
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        async def setup(extra=''):
            await ev(pg,"()=>{const G=__T.G;for(let y=104;y<118;y++)for(let x=104;x<118;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=1}G.enemies.length=0;G.fish=null;G.inv.fill(null);G.p.x=110.5;G.p.y=110.5;G.p.face={x:1,y:0};G.sel=5;"+extra+"}")
            await pg.wait_for_timeout(150)
        r=await ev(pg,"()=>{const ids=['Thin','Half','Win','Frame','Fence','Door','Pillar'];return ['Wood','Stone'].every(m=>ids.every(t=>__T.RECIPES.some(r=>r.out==='b'+t+m&&r.at==='bench'&&r.cat==='build')))&&!__T.RECIPES.some(r=>/^roof/.test(r.out))}")
        rec('제작','나무·돌 각각 7종 제작법 (작업대·건축 탭), 지붕은 v41에서 삭제', r)
        r=await ev(pg,"()=>[__T.ITEMS.bThinWood.n,__T.ITEMS.bDoorStone.n]")
        rec('제작','이름', r==['나무 얇은 벽','돌 문'], str(r))
        # place thin walls by holding while walking
        await setup("__T.addItem('bThinWood',5);G.sel=G.inv.findIndex(s=>s&&s.id==='bThinWood');")
        r=await ev(pg,"()=>[__T.decide().k,__T.decide().lbl]")
        rec('설치','얇은 벽 들고 → 놓기', r==['place','놓기'], str(r))
        await tap(pg,1); r=await ev(pg,"()=>__T.G.objs.get(__T.idx(111,110))?.t")
        rec('설치','얇은 벽 설치', r=='bThinWood', r)
        r=await ev(pg,"()=>[__T.decide().k, __T.decide().sub]")
        rec('설치','이미 있는 칸 앞: 회수 대신 안내 + 작은 [회수] 버튼', r==['info',True], str(r))
        # door
        await setup("G.objs.set(__T.idx(111,110),{t:'bDoorWood'});")
        r=await ev(pg,"()=>[__T.decide().k,__T.decide().lbl]")
        rec('문','문 앞 → 열기', r==['use','열기'], str(r))
        await tap(pg,1); r=await ev(pg,"()=>[!!__T.G.objs.get(__T.idx(111,110)).open, __T.decide().lbl]")
        rec('문','열리고 버튼은 닫기로', r==[True,'닫기'], str(r))
        # walk through open door
        await ev(pg,"()=>{const G=__T.G;G.objs.set(__T.idx(111,109),{t:'bThinWood'});G.objs.set(__T.idx(111,111),{t:'bThinWood'})}")
        await pg.keyboard.down('d'); await pg.wait_for_timeout(700); await pg.keyboard.up('d')
        x1=await ev(pg,"()=>__T.G.p.x")
        rec('문','열린 문은 지나갈 수 있음', x1>111.6, x1)
        await setup("G.objs.set(__T.idx(111,110),{t:'bDoorWood'});")
        await pg.keyboard.down('d'); await pg.wait_for_timeout(700); await pg.keyboard.up('d')
        x2=await ev(pg,"()=>__T.G.p.x")
        rec('문','닫힌 문은 막힘', x2<111, x2)
        await ev(pg,"()=>{const G=__T.G;G.objs.get(__T.idx(111,110)).open=1;G.p.x=111.5;G.p.y=110.5;G.p.face={x:1,y:0}}")
        r=await ev(pg,"()=>{const G=__T.G,o=G.objs.get(__T.idx(111,110));G.p.face={x:0,y:0};return 0}")
        await ev(pg,"()=>{const G=__T.G;G.p.x=110.5;G.p.face={x:1,y:0};G.p.x=111.2}")  # standing inside doorway
        await ev(pg,"()=>{}")
        await setup("G.objs.set(__T.idx(111,110),{t:'bDoorWood',open:1});G.p.x=110.85;")
        await tap(pg,1); r=await ev(pg,"()=>[!!__T.G.objs.get(__T.idx(111,110)).open, document.querySelector('#toasts').innerText.includes('문 사이에')]")
        rec('문','문턱에 걸쳐 서 있으면 닫히지 않음', r==[True,True], str(r))
        # save (roofs were removed in v41 — see qa41)
        r=await ev(pg,"()=>{const G=__T.G;G.objs.set(__T.idx(111,110),{t:'bDoorStone',open:1});const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);const o=__T.G.objs.get(__T.idx(111,110));return [o.t,!!o.open,'roof' in s]}")
        rec('저장','문 저장/불러오기 (지붕 항목 없음)', r==['bDoorStone',True,False], str(r))
        # icons are 16x16
        r=await ev(pg,"()=>{__T.openPanel('craft');return 1}"); await pg.wait_for_timeout(400)
        await pg.click('#sheet [data-a=tab][data-i=build]'); await pg.wait_for_timeout(300)
        await pg.evaluate("()=>{document.querySelector('#sheet .sh-body').scrollTop=500}"); await pg.wait_for_timeout(200)
        await pg.screenshot(path=SP+'qa12_craft.png')
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
