import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
async def main():
    mkpage(SRC,'qa.html')
    async with async_playwright() as p:
        b=await p.chromium.launch(); errs=[]
        ctx=await b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,has_touch=True,is_mobile=True)
        pg=await ctx.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
        await pg.goto('file://'+SP+'qa.html'); await pg.wait_for_timeout(500)
        await pg.tap('#btnNew'); await pg.wait_for_timeout(300)
        rec('꾸미기','선택 화면에 직접 꾸미기 카드', await ev(pg,"()=>!!document.querySelector('#cpGrid [data-c=custom]') && document.querySelector('#cpGrid [data-c=custom] span').textContent==='직접 꾸미기'"))
        await pg.tap('#cpGrid [data-c=custom]'); await pg.tap('#charGo'); await pg.wait_for_timeout(900)
        r=await ev(pg,"()=>[__T.G.char, document.querySelector('#sheet h2')?.textContent]")
        rec('꾸미기','직접 꾸미기로 시작하면 꾸미기 창이 바로 열림', r==['custom','꾸미기'], str(r))
        n=await ev(pg,"()=>document.querySelectorAll('#sheet .look-opt').length")
        rec('꾸미기','머리 모양 8가지', n==8, n)
        await pg.screenshot(path=SP+'qa13_hair.png')
        await pg.tap('#sheet .look-opt[data-i="hair:buns"]'); await pg.wait_for_timeout(200)
        await pg.tap('#sheet [data-a=lookTab][data-i=hc]'); await pg.wait_for_timeout(200); await pg.tap('#sheet .look-opt[data-i="hc:5"]'); await pg.wait_for_timeout(200)
        await pg.tap('#sheet [data-a=lookTab][data-i=outfit]'); await pg.wait_for_timeout(200); await pg.tap('#sheet .look-opt[data-i="outfit:apron"]'); await pg.wait_for_timeout(200)
        await pg.tap('#sheet [data-a=lookTab][data-i=oc]'); await pg.wait_for_timeout(200); await pg.tap('#sheet .look-opt[data-i="oc:3"]'); await pg.wait_for_timeout(200)
        await pg.tap('#sheet [data-a=lookTab][data-i=hat]'); await pg.wait_for_timeout(200); await pg.tap('#sheet .look-opt[data-i="hat:flowers"]'); await pg.wait_for_timeout(200)
        await pg.screenshot(path=SP+'qa13_hat.png')
        r=await ev(pg,"()=>__T.G.look.hair")
        rec('꾸미기','적용 전에는 바뀌지 않음', r=='bob', r)
        await pg.tap('#sheet [data-a=lookOk]'); await pg.wait_for_timeout(400)
        r=await ev(pg,"()=>[__T.G.char, JSON.stringify(__T.serialize().look), document.querySelector('#sheetWrap').hidden]")
        rec('꾸미기','이 모습으로 하기 → 적용 + 저장', r[0]=='custom' and '"hair":"buns"' in r[1] and '"hat":"flowers"' in r[1] and '"oc":3' in r[1] and r[2], str(r))
        r=await ev(pg,"()=>{const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);const a=__T.G.look.hair;s.look={hair:'zzz',hc:99};__T.deserialize(s);const b=[__T.G.look.hair,__T.G.look.hc];delete s.look;s.char='momo';__T.deserialize(s);return [a,b,__T.G.char]}")
        rec('저장','꾸민 모습 저장 / 잘못된 값은 기본값 / 예전 세이브 정상', r==['buns',['bob',8],'momo'], str(r))
        # wardrobe furniture opens panel
        await ev(pg,"()=>{const G=__T.G;G.char='custom';G.objs.set(__T.idx(Math.floor(G.p.x)+1,Math.floor(G.p.y)),{t:'shroomWardrobe'});G.p.face={x:1,y:0}}"); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.decide().k,__T.decide().lbl]")
        rec('가구','옷장 → 꾸미기', r==['use','꾸미기'], str(r))
        await tap(pg,1); await pg.wait_for_timeout(500)
        rec('가구','옷장을 쓰면 꾸미기 창', await ev(pg,"()=>document.querySelector('#sheet h2')?.textContent")=='꾸미기')
        await pg.tap('#sheet [data-a=close]'); await pg.wait_for_timeout(300)
        await ev(pg,"()=>{document.getElementById('toasts').style.display='none'}"); await pg.wait_for_timeout(300); await pg.screenshot(path=SP+'qa13_game.png')
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
