import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
async def main():
    mkpage(SRC,'qa.html')
    async with async_playwright() as p:
        b=await p.chromium.launch(); errs=[]
        ctx=await b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,has_touch=True,is_mobile=True)
        pg=await ctx.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
        await pg.goto('file://'+SP+'qa.html'); await pg.wait_for_timeout(400)
        await pg.tap('#btnNew'); await pg.wait_for_timeout(200)
        rec('보호','세이브가 없으면 확인 없이 바로 캐릭터 선택', await ev(pg,"()=>!document.querySelector('#charPick').hidden"))
        await pg.tap('#charGo'); await pg.wait_for_timeout(600)
        await ev(pg,"()=>{__T.addItem('crystal',42);__T.G.stats.wood=77}"); await ev(pg,"()=>__T.openPanel('menu')"); await pg.wait_for_timeout(400); await pg.click('#sheet [data-a=save]'); await pg.wait_for_timeout(200)
        await pg.reload(); await pg.wait_for_timeout(600)
        await pg.tap('#btnNew'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[document.querySelector('#charPick').hidden, document.querySelector('#btnNew').textContent]")
        rec('보호','세이브가 있으면 새 모험 전에 한 번 더 확인', r[0] and '정말 새로 시작할까요' in r[1], str(r))
        await pg.tap('#btnNew'); await pg.wait_for_timeout(200); await pg.tap('#charGo'); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>{const b=JSON.parse(localStorage.getItem('lantern-tree-backups')||'[]');return [b.length, b[0]&&b[0].reason, b[0]&&JSON.parse(b[0].data).stats.wood, __T.countItem('crystal')]}")
        rec('백업','새로 시작하면 이전 세이브가 백업됨', r[0]==1 and r[1]=='새 모험 시작 전' and r[2]==77 and r[3]==0, str(r))
        await pg.reload(); await pg.wait_for_timeout(600)
        rec('백업','첫 화면에 백업에서 되돌리기 버튼', await ev(pg,"()=>!document.querySelector('#btnBackups').hidden"))
        await pg.tap('#btnBackups'); await pg.wait_for_timeout(200); await pg.screenshot(path=SP+'qa14_backups.png')
        await pg.tap('#bkList [data-bk="0"]'); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>[document.querySelector('#title').hidden, __T.countItem('crystal'), __T.G.stats.wood, JSON.parse(localStorage.getItem('lantern-tree-backups')).length]")
        rec('백업','되돌리면 6시간짜리(?) 세이브 복구 + 지금 것도 백업', r[0] and r[1]==42 and r[2]==77 and r[3]==2, str(r))
        # menu restart backs up
        await ev(pg,"()=>__T.openPanel('menu')"); await pg.wait_for_timeout(700); await pg.click('#sheet [data-a=newgame]'); await pg.wait_for_timeout(100)
        t=await ev(pg,"()=>document.querySelector('#sheet [data-a=newgame]').textContent"); await pg.click('#sheet [data-a=newgame]'); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>{const b=JSON.parse(localStorage.getItem('lantern-tree-backups'));return [b.length,b[0].reason]}")
        rec('백업','메뉴에서 처음부터 다시 하기도 백업 (최대 3개)', '백업돼요' in t and r==[3,'처음부터 다시 하기 전'], f'{t} {r}')
        await ctx.close()
        # storage blocked
        ctx=await b.new_context(viewport={'width':390,'height':844},has_touch=True,is_mobile=True)
        await ctx.add_init_script("Object.defineProperty(window,'localStorage',{get(){throw new Error('blocked')}})")
        pg=await ctx.new_page(); pg.on('pageerror',lambda e: errs.append('blocked-ctx: '+str(e)))
        await pg.goto('file://'+SP+'qa.html'); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>[!document.querySelector('#saveWarn').hidden, document.querySelector('#saveWarn').textContent.slice(0,22)]")
        rec('경고','저장이 막힌 환경이면 첫 화면에 경고', r[0], str(r))
        await pg.screenshot(path=SP+'qa14_warn.png')
        await pg.tap('#btnNew'); await pg.wait_for_timeout(200); await pg.tap('#charGo'); await pg.wait_for_timeout(800)
        r=await ev(pg,"()=>document.querySelector('#toasts').innerText.includes('저장이 되지 않아요')")
        rec('경고','플레이 중 자동 저장이 실패하면 알림', r)
        await ctx.close()
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
