import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,give:(id)=>{const i=G.inv.findIndex((s,k)=>k<9&&!s);G.inv[i]={id,c:1};if(DUR[id])G.inv[i].dur=DUR[id][0];invDirty=true},GUIDE,RECIPES,nearStations,canCraft,checkGuide,gainXp,maxHp,maxMp,useSkill,SKILLS,XP_NEED,WTYPE,curWeapon,perform,swingAttack,targetTile,canPlace:typeof canPlace!=='undefined'?canPlace:null}")
ARENA="()=>{const G=__T.G;for(let y=100;y<120;y++)for(let x=100;x<122;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=1}G.enemies.length=0;G.p.x=105.5;G.p.y=110.5;G.p.face={x:1,y:0};G.p.dir='side';G.p.hp=__T.maxHp();G.p.mp=__T.maxMp();for(let i=0;i<30;i++)G.inv[i]=null;G.sel=0}"
EN="(x,y,hp)=>{__T.G.enemies.push({k:'slimeG',x,y,hp:hp||999,vx:0,vy:0,t:99,hurt:0,kx:0,ky:0,z:0,air:0,airMax:.42,land:0,cd:99,anim:0})}"
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        # ---- quest order ----
        r=await ev(pg,"()=>{const G=__T.G;Object.assign(G.stats,{wood:6,bench:1,torch:1,copperOre:6,copperBar:1,forge:1});__T.addItem('pickCopper',1);G.guide=0;__T.checkGuide();const a=document.querySelector('#goalTxt').textContent;G.bossDead.queen=true;__T.checkGuide();const b=document.querySelector('#goalTxt').textContent;return [a,b]}")
        rec('퀘스트','버섯 여왕이 먼저', '버섯 여왕' in r[0], r[0]); rec('퀘스트','여왕 다음 말랑대왕', '말랑대왕' in r[1], r[1])
        r=await ev(pg,"()=>{const G=__T.G;G.bossDead.queen=false;G.bossDead.slime=true;const s=__T.serialize();s.guide=8;__T.deserialize(s);__T.checkGuide();return document.querySelector('#goalTxt').textContent}")
        rec('퀘스트','예전 세이브(말랑대왕만 잡음)도 여왕부터 안내', '버섯 여왕' in r, r)
        r=await ev(pg,"()=>{const G=__T.G;Object.assign(G.stats,{forge:0});for(let i=0;i<30;i++)G.inv[i]=null;G.bossDead.slime=false;G.guide=0;__T.checkGuide();return document.querySelector('#goalTxt').textContent}")
        rec('퀘스트','구리 제작대 단계 추가', '구리 제작대' in r, r)
        r=await ev(pg,"()=>[__T.BOSSES.queen.hp,__T.BOSSES.slime.hp]")
        rec('퀘스트','난이도: 여왕 < 대왕', r[0]<r[1], str(r))
        # ---- workbench tier & recipes ----
        r=await ev(pg,"()=>{const at=id=>__T.RECIPES.find(r=>r.out===id).at;return [at('pickCopper'),at('swordIron'),at('pot'),at('shovel'),at('chest'),at('furnace'),at('forge'),at('torch'),at('rope'),at('spearWood'),at('copperLamp')]}")
        rec('제작대','구리 이상은 구리 제작대', r[:4]==['forge']*4 and r[10]=='forge', str(r))
        rec('제작대','초기 제작은 그대로 (작업대/손)', r[4:10]==['bench','bench','bench',None,None,'bench'], str(r))
        r=await ev(pg,"()=>{const metal=['copperBar','ironBar','crystal'];return __T.RECIPES.filter(r=>r.at==='bench'&&r.out!=='forge'&&r.req.some(([i])=>metal.includes(i))).map(r=>r.out)}")
        rec('제작대','작업대에 구리·철·수정 레시피가 남지 않음', r==[], str(r))
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;['copperBar','wood','rope'].forEach(i=>__T.addItem(i,20));G.objs.set(__T.idx(107,110),{t:'bench'});const R=__T.RECIPES.find(r=>r.out==='pickCopper');__T.openPanel('craft',{st:'bench'});const a=__T.canCraft(R,__T.nearStations());G.objs.set(__T.idx(107,112),{t:'forge'});__T.closePanel();__T.openPanel('craft',{st:'forge'});const b=__T.canCraft(R,__T.nearStations());__T.closePanel();return [a,b]}")
        rec('제작대','작업대만 있으면 구리 곡괭이 불가, 구리 제작대 옆이면 가능', r==[False,True], str(r))
        r=await ev(pg,"()=>{const n=r=>r.req.length;const f=id=>n(__T.RECIPES.find(r=>r.out===id));return [f('pickCopper'),f('swordCopper'),f('chest'),f('bed'),f('rod')]}")
        rec('재료','레시피 재료 종류가 늘어남', all(x>=2 for x in r) and r[0]>=3 and r[2]>=2, str(r))
        r=await ev(pg,"()=>[__T.OBJ.root.drops.some(d=>d[0]==='resin'),!!__T.ITEMS.rope,!!__T.ITEMS.resin]")
        rec('재료','송진(뿌리기둥) · 이끼 끈 추가', r==[True,True,True], str(r))
        # open the forge and look at the weapon tab
        await ev(pg,"()=>{__T.G.p.face={x:0,y:1};__T.G.p.x=107.5;__T.G.p.y=111.5}"); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>__T.decide().k"); rec('제작대','구리 제작대 앞에서 열기', r=='open', r)
        await tap(pg,1); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>document.querySelector('.sh-head h2').textContent"); rec('제작대','구리 제작대 창이 열림', '구리 제작대' in r, r)
        await pg.screenshot(path=SP+'qa17_forge.png')
        await pg.tap('[data-a=tab][data-i=weapon]'); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>[...document.querySelectorAll('.rc .rn')].map(e=>e.childNodes[0].textContent)")
        rec('무기','무기 탭에 여러 종류', all(any(k in x for x in r) for k in ['창','망치','활','지팡이','단검','검']), ','.join(r))
        await pg.screenshot(path=SP+'qa17_weapons.png')
        await ev(pg,"()=>__T.closePanel()")
        # ---- weapons ----
        await ev(pg,ARENA); await ev(pg,"()=>{__T.give('spearWood');__T.give('swordWood');__T.G.sel=0}")
        await ev(pg,"()=>{const f="+EN+";f(107.5,110.5)}")
        r=await ev(pg,"()=>{const a=__T.decide().k;__T.G.sel=1;const b=__T.decide().k;return [a,b]}")
        rec('무기','창은 2칸 떨어진 적도 공격, 검은 닿지 않음', r==['attack','swing'], str(r))
        r=await ev(pg,"()=>{__T.G.sel=0;const e=__T.G.enemies[0];const h=e.hp;__T.perform(__T.decide());return [h-e.hp>0, __T.G.swing&&__T.G.swing.wt]}")
        rec('무기','창 찌르기 명중', r[0] and r[1]=='spear', str(r))
        await ev(pg,ARENA); await ev(pg,"()=>{__T.give('bowWood');__T.G.sel=0;const f="+EN+";f(110.5,110.5)}")
        r=await ev(pg,"()=>{const d=__T.decide();return [d.k,d.lbl]}")
        rec('무기','활: 5칸 앞 적 → 쏘기', r==['attack','쏘기'], str(r))
        r=await ev(pg,"()=>{__T.perform(__T.decide());return __T.G.pshots.length}")
        rec('무기','화살이 날아감', r==1, r)
        await pg.wait_for_timeout(700)
        r=await ev(pg,"()=>[__T.G.enemies[0].hp<999, __T.G.pshots.length]")
        rec('무기','화살이 적에게 맞음', r[0] and r[1]==0, str(r))
        await ev(pg,ARENA); await ev(pg,"()=>{__T.G.wall[__T.idx(108,110)]=2;__T.give('bowWood');__T.G.sel=0;const f="+EN+";f(111.5,110.5)}")
        r=await ev(pg,"()=>__T.decide().k"); rec('무기','벽 너머 적은 자동 조준 안 함', r!='attack', r)
        await ev(pg,ARENA); await ev(pg,"()=>{__T.give('staffGlow');__T.G.sel=0;const f="+EN+";f(109.5,110.5);f(111,110.5)}")
        r=await ev(pg,"()=>{const m=__T.G.p.mp;__T.perform(__T.decide());return [m-__T.G.p.mp,__T.G.pshots[0]&&__T.G.pshots[0].pierce]}")
        rec('무기','지팡이: 기력 4 소모, 관통 구슬', r[0]>3.9 and r[1]==1, str(r))
        await pg.wait_for_timeout(900)
        r=await ev(pg,"()=>__T.G.enemies.map(e=>e.hp<999)"); rec('무기','구슬이 두 적을 꿰뚫음', len(r)>=2 and all(r), str(r))
        await ev(pg,ARENA); await ev(pg,"()=>{__T.give('hammerCopper');__T.G.sel=0;const f="+EN+";f(106.3,110.5);f(105.5,111.4)}")
        r=await ev(pg,"()=>{__T.perform(__T.decide());return __T.G.enemies.map(e=>e.hp<999)}")
        rec('무기','망치: 넓게 휘둘러 두 적 모두 맞힘', r==[True,True], str(r))
        r=await ev(pg,"()=>{__T.G.inv[0]=null;__T.give('swordCopper');__T.give('spearIron');for(let i=0;i<6;i++)if(!__T.G.inv[i]){__T.G.sel=i;break}return __T.curWeapon().id}")
        rec('무기','아무것도 안 들면 검을 자동으로 사용', r=='swordCopper', r)
        # ---- level & stats ----
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.rpg.lv=1;G.rpg.xp=0;G.rpg.pts=0;G.rpg.sp=0;G.p.hp=40;__T.gainXp(25);return [G.rpg.lv,G.rpg.pts,G.rpg.sp,G.p.hp===__T.maxHp(),G.rpg.xp]}")
        rec('레벨','경험치 25 → Lv.2, 포인트 2·스킬 1, 체력 회복', r==[2,2,1,True,5], str(r))
        r=await ev(pg,"()=>{const G=__T.G,x=G.rpg.xp;const f="+EN+";f(106.3,110.5,1);__T.give('swordWood');__T.perform({k:'swing'});return [G.enemies.length,G.rpg.xp-x]}")
        rec('레벨','몬스터를 물리치면 경험치', r[0]==0 and r[1]>0, str(r))
        await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>document.querySelector('#bStat').classList.contains('dot')"); rec('능력','포인트가 있으면 능력 버튼에 점', r, r)
        await pg.tap('#bStat'); await pg.wait_for_timeout(600)
        await pg.tap('[data-a=statUp][data-i=vit]'); await pg.wait_for_timeout(150)
        r=await ev(pg,"()=>[__T.G.rpg.vit,__T.maxHp(),__T.G.rpg.pts]"); rec('능력','체력 +1 → 최대 체력 108', r==[1,108,1], str(r))
        r=await ev(pg,"()=>document.querySelector('[data-a=skUp][data-i=spin]').disabled"); rec('능력','레벨이 모자란 스킬은 못 배움', r, r)
        await pg.tap('[data-a=skUp][data-i=dash]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.G.rpg.sk.dash,__T.G.rpg.slot[0],__T.G.rpg.sp]"); rec('스킬','구르기 배우면 첫 칸에 자동으로', r==[1,'dash',0], str(r))
        await pg.screenshot(path=SP+'qa17_stat.png')
        await ev(pg,"()=>__T.closePanel()"); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>!document.querySelector('#skBar').hidden"); rec('스킬','스킬 버튼이 나타남', r, r)
        r=await ev(pg,"()=>{const G=__T.G,x=G.p.x,m=G.p.mp;G.p.face={x:1,y:0};__T.useSkill(0);return [!!G.p.dash,m-G.p.mp,G.p.inv>0.3]}")
        rec('스킬','구르기: 이동·기력 소모·무적', r==[True,10,True], str(r))
        await pg.wait_for_timeout(400)
        r=await ev(pg,"()=>[__T.G.p.x>107,__T.G.skcd.dash>0]"); rec('스킬','구르기로 앞으로 이동, 재사용 대기', r==[True,True], str(r))
        await pg.screenshot(path=SP+'qa17_skbar.png')
        r=await ev(pg,"()=>{const m=__T.G.p.mp;__T.useSkill(0);return __T.G.p.mp===m}"); rec('스킬','대기 중엔 다시 안 써짐', r, r)
        # quake & heal
        r=await ev(pg,"()=>{const G=__T.G;G.rpg.lv=6;G.rpg.sk.quake=1;G.rpg.sk.heal=1;G.rpg.slot=['quake','heal'];G.skcd={};G.p.x=105.5;G.p.y=110.5;G.p.face={x:1,y:0};for(let y=109;y<=111;y++)for(let x=107;x<=109;x++)G.wall[__T.idx(x,y)]=1;__T.addItem('pickWood',1);G.p.mp=__T.maxMp();__T.useSkill(0);let n=0;for(let y=109;y<=111;y++)for(let x=107;x<=109;x++)n+=G.wall[__T.idx(x,y)]?1:0;return n}")
        rec('스킬','광맥 부수기: 앞쪽 벽 여러 칸이 한 번에', r<=3, f'남은 벽 {r}/9')
        r=await ev(pg,"()=>{const G=__T.G;G.p.hp=30;G.p.mp=__T.maxMp();__T.useSkill(1);return G.p.hp>30}"); rec('스킬','등불 치유로 체력 회복', r, r)
        # passives
        r=await ev(pg,"()=>{const G=__T.G;G.rpg.sk.tough=3;G.p.hp=100;G.p.inv=0;G.p.dead=0;const e={x:G.p.x+.2,y:G.p.y};const h=G.p.hp;__T.G.enemies.length=0;return h}")
        # save round trip
        r=await ev(pg,"()=>{const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);const R=__T.G.rpg;return [R.lv,R.vit,R.sk.dash,R.slot[0]]}")
        rec('저장','레벨·능력치·스킬이 저장됨', r==[6,1,1,'quake'], str(r))
        r=await ev(pg,"()=>{const s=__T.serialize();delete s.rpg;__T.deserialize(s);return [__T.G.rpg.lv,__T.maxHp()]}")
        rec('저장','예전 세이브는 Lv.1로 시작', r==[1,100], str(r))
        # layout with skill buttons on several screens
        await ev(pg,"()=>{const G=__T.G;G.rpg.sk.dash=1;G.rpg.sk.spin=1;G.rpg.slot=['dash','spin']}")
        rec('기능','콘솔 오류 없음 (모바일)', not errs, errs[:3]); await ctx.close()
        for (w,h,touch,name) in [(390,844,True,'iPhone 14'),(360,640,True,'small Android'),(375,667,True,'iPhone SE'),(844,390,True,'phone landscape'),(1280,800,False,'laptop'),(1024,768,False,'small desktop')]:
            ctx,pg,errs=await new_ctx(b,w,h,touch)
            await ev(pg,"()=>{const G=__T.G;G.rpg.sk.dash=1;G.rpg.sk.spin=1;G.rpg.slot=['dash','spin'];G.rpg.pts=2}")
            if touch: await ev(pg,"()=>document.body.classList.add('touch')")
            await ev(pg,"()=>{const G=__T.G;G.objs.set(__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1),{t:'chair'});G.p.face={x:0,y:1}}")
            await pg.wait_for_timeout(500)
            r=await ev(pg,"""()=>{const q=s=>{const e=document.querySelector(s);if(!e)return null;const cs=getComputedStyle(e);if(e.hidden||cs.display==='none')return null;const r=e.getBoundingClientRect();return r.width?{x:r.left,y:r.top,r:r.right,b:r.bottom}:null};
              const E={sk:q('#skBar'),act:q('#actBtn'),sub:q('#subBtn'),hot:q('#hotbar'),bars:q('#hud .bars'),side:q('#hud .side'),joy:q('#joy'),hint:q('#pcHint')};const ov=(a,b)=>a&&b&&a.x<b.r-1&&b.x<a.r-1&&a.y<b.b-1&&b.y<a.b-1;
              const bad=Object.keys(E).filter(k=>k!=='sk'&&ov(E.sk,E[k]));const out=E.sk&&(E.sk.x<0||E.sk.y<0||E.sk.r>innerWidth||E.sk.b>innerHeight);const sideOut=E.side&&(E.side.b>innerHeight||E.side.r>innerWidth);return [!!E.sk,bad,!!out,!!sideOut,!!(E.bars&&E.side&&ov(E.bars,E.side))]}""")
            rec('레이아웃',f'{name} 스킬 버튼 겹침 없음', r[0] and not r[1] and not r[2], str(r))
            rec('레이아웃',f'{name} 능력 버튼 포함 사이드 메뉴가 화면 안', not r[3] and not r[4], str(r))
            await pg.screenshot(path=SP+f'qa17_layout_{w}x{h}.png')
            rec('기능',f'{name} 콘솔 오류 없음', not errs, errs[:3]); await ctx.close()
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
