import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,RECIPES,ENEMY,FLOWERS,zoneTick,growTick,perform,canPlace,isSolid,mkEnemy,hitEnemy,genFlowerZones,maxHp,FLOOR_ITEM,refreshHotbar}")
ARENA="()=>{const G=__T.G;for(let y=96;y<124;y++)for(let x=96;x<126;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=1}G.enemies.length=0;G.drops.length=0;G.p.x=105.5;G.p.y=110.5;G.p.face={x:1,y:0};G.p.dir='side';G.p.hp=__T.maxHp();for(let i=0;i<30;i++)G.inv[i]=null;G.sel=0;G.fzones=[{x:112,y:110,c:'R',dead:[]}]}"
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        # ---------- petals & zones ----------
        r=await ev(pg,"()=>{const c=Object.keys(__T.FLOWERS);return [c.every(k=>__T.ITEMS['petal'+k]&&__T.ENEMY['bloom'+k]),c.map(k=>__T.ITEMS['petal'+k].n).join(',')]}")
        rec('꽃잎','꽃잎 5색 + 꽃망울 5종', r[0], r[1])
        r=await ev(pg,"()=>{const G=__T.G,z=G.fzones;return [z.length,z.every(q=>G.biome[__T.idx(q.x,q.y)]===0),[...new Set(z.map(q=>q.c))].sort().join('')]}")
        rec('구역','꽃망울 구역이 이끼 동굴에 색깔별로 생성', r[0]>=8 and r[1] and r[2]=='BKRWY', str(r))
        r=await ev(pg,"()=>{const G=__T.G,out=[];for(let k=0;k<25;k++){G.seed=1000+k*7919;const z=__T.genFlowerZones();out.push([z.length,new Set(z.map(q=>q.c)).size])}return out}")
        rec('구역','여러 세계에서도 5색 구역이 모두 생김', all(a>=8 and b2==5 for a,b2 in r), str(r))
        r=await ev(pg,"()=>{const G=__T.G,z=G.fzones;let ok=true;for(let a=0;a<z.length;a++)for(let b=a+1;b<z.length;b++)if(Math.hypot(z[a].x-z[b].x,z[a].y-z[b].y)<13)ok=false;return ok}")
        rec('구역','구역끼리 겹치지 않음', r, r)
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;for(let k=0;k<12;k++){G.time+=2;__T.zoneTick()}return G.enemies.filter(e=>e.zone===0).map(e=>e.k)}")
        rec('구역','구역에서 꽃망울이 최대 3마리까지 젠', len(r)==3 and all(k=='bloomR' for k in r), str(r))
        r=await ev(pg,"()=>{const G=__T.G;return G.enemies.every(e=>Math.hypot(e.x-112.5,e.y-110.5)<4.5)}")
        rec('구역','젠 위치가 구역 안', r, r)
        # calm behaviour
        r=await ev(pg,"()=>{const G=__T.G;const e=G.enemies[0];e.x=G.p.x+.3;e.y=G.p.y;G.p.inv=0;const h=G.p.hp;return h}")
        await pg.wait_for_timeout(1200)
        r2=await ev(pg,"()=>__T.G.p.hp")
        rec('꽃망울','먼저 때리지 않으면 공격하지 않음', r2==r, f'{r}->{r2}')
        r=await ev(pg,"()=>{const G=__T.G;const e=G.enemies[0];__T.hitEnemy(e,1,false);return e.angry>0}")
        rec('꽃망울','맞으면 화가 나서 반격', r, r)
        # kill → petal + respawn after a while
        r=await ev(pg,"()=>{const G=__T.G;G.drops.length=0;const e=G.enemies.find(e=>e.zone===0);__T.hitEnemy(e,999,false);return [G.drops.some(d=>d.id==='petalR'),G.fzones[0].dead.length]}")
        rec('꽃망울','쓰러뜨리면 빨간 꽃잎', r[0], str(r)); rec('구역','쓰러진 자리는 리젠 대기', r[1]==1, str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.time+=5;__T.zoneTick();__T.zoneTick();const a=G.enemies.filter(e=>e.zone===0).length;G.time+=45;__T.zoneTick();const b=G.enemies.filter(e=>e.zone===0).length;return [a,b]}")
        rec('구역','45초 뒤 다시 젠', r==[2,3], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.enemies.forEach(e=>{e.angry=0});const e=G.enemies.find(e=>e.zone===0);e.x=118.5;e.y=110.5;e.t=0;return 1}")
        await pg.wait_for_timeout(2500)
        r=await ev(pg,"()=>{const G=__T.G;return Math.max(...G.enemies.filter(e=>e.zone===0).map(e=>Math.hypot(e.x-112.5,e.y-110.5)))}")
        rec('꽃망울','구역 밖으로 나가면 돌아옴', r<5.5, f'{r:.2f}')
        # ---------- regrowth ----------
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.fzones=[];const i=__T.idx(107,110);G.objs.set(i,{t:'root'});__T.addItem('pickWood',1);for(let k=0;k<6;k++)__T.perform({k:'chop',t:{x:107,y:110},o:G.objs.get(i)});return G.objs.get(i)&&G.objs.get(i).t}")
        rec('리젠','뿌리기둥을 베면 그루터기가 남음', r=='stump', r)
        r=await ev(pg,"()=>{const G=__T.G;G.p.x=106.5;G.p.face={x:1,y:0};const d=__T.decide();return [d.k,d.lbl]}")
        rec('리젠','그루터기 앞 → 자라는 중 안내', r==['info','자라는 중'], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.time+=241;__T.growTick();return G.objs.get(__T.idx(107,110)).t}")
        rec('리젠','4분 뒤 뿌리기둥이 다시 자람', r=='root', r)
        r=await ev(pg,"()=>{const G=__T.G;const i=__T.idx(105,110);G.p.x=105.5;G.objs.set(i,{t:'stump',g:'root',at:G.time-1});__T.growTick();return G.objs.get(i).t}")
        rec('리젠','플레이어가 서 있는 칸은 자라지 않음(갇힘 방지)', r=='stump', r)
        r=await ev(pg,"()=>{const G=__T.G;const i=__T.idx(108,112);G.objs.set(i,{t:'grass'});__T.perform({k:'chop',t:{x:108,y:112},o:G.objs.get(i)});const a=!!G.objs.get(i);G.time+=121;__T.growTick();return [a,G.objs.get(i)&&G.objs.get(i).t]}")
        rec('리젠','이끼풀도 2분 뒤 다시 자람', r==[False,'grass'], str(r))
        # ---------- saplings ----------
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.fzones=[];__T.addItem('sapling',2);G.sel=G.inv.findIndex(s=>s&&s.id==='sapling');const d=__T.decide();__T.perform(d);return [d.k,G.objs.get(__T.idx(106,110))&&G.objs.get(__T.idx(106,110)).t]}")
        rec('묘목','묘목을 이끼 바닥에 심기', r==['place','sapling'], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.floor[__T.idx(104,110)]=5;G.p.face={x:-1,y:0};return __T.decide().k}")
        rec('묘목','나무 바닥에는 못 심음', r!='place', r)
        r=await ev(pg,"()=>{const G=__T.G;G.time+=181;__T.growTick();return G.objs.get(__T.idx(106,110)).t}")
        rec('묘목','3분 뒤 뿌리기둥으로 자람', r=='root', r)
        r=await ev(pg,"()=>!!__T.RECIPES.find(r=>r.out==='sapling')&&__T.OBJ.root.drops.some(d=>d[0]==='sapling')")
        rec('묘목','묘목 얻는 법: 제작 + 뿌리기둥에서 가끔', r, r)
        # ---------- berry bush with shovel ----------
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.fzones=[];G.objs.set(__T.idx(106,110),{t:'bush'});__T.addItem('shovel',1);G.sel=G.inv.findIndex(s=>s&&s.id==='shovel');G.p.face={x:1,y:0};const d=__T.decide();__T.perform(d);return [d.k,d.lbl,!!G.objs.get(__T.idx(106,110)),__T.countItem('berryBush')]}")
        rec('덤불','삽으로 열매덤불 퍼내기', r==['dig','퍼내기',False,1], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.sel=G.inv.findIndex(s=>s&&s.id==='berryBush');const d=__T.decide();__T.perform(d);const o=G.objs.get(__T.idx(106,110));return [d.k,o&&o.t,o&&o.r>G.time]}")
        rec('덤불','옮겨 심기 (바로 열매는 안 열림)', r==['place','bush',True], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.sel=G.inv.findIndex(s=>s&&s.id==='shovel');G.objs.set(__T.idx(106,110),{t:'stump',g:'root',at:G.time+99});const d=__T.decide();__T.perform(d);return [d.lbl,!!G.objs.get(__T.idx(106,110))]}")
        rec('덤불','삽으로 그루터기 뽑기', r==['뽑기',False], str(r))
        # ---------- nature decorations ----------
        r=await ev(pg,"()=>{const R=id=>__T.RECIPES.find(r=>r.out===id);const ids=r=>r.req.map(x=>x[0]).sort().join(',');const tot=r=>r.req.reduce((a,x)=>a+x[1],0);return {cherry:ids(R('cherryTree')),cherryN:tot(R('cherryTree')),tile:ids(R('floorCherry')),tileN:tot(R('floorCherry')),tree:ids(R('roundTree')),shrub:ids(R('shrub')),bed:ids(R('flowerBed')),water:__T.RECIPES.filter(r=>r.out.startsWith('water')).length}}")
        rec('꾸미기','벚꽃나무: 흙·이끼·나무·흰·빨간 꽃잎 (재료 많음)', r['cherry']=='dirt,gMoss,petalR,petalW,wood' and r['cherryN']>=30, str(r))
        rec('꾸미기','벚꽃 타일: 흙·이끼·흰·빨간 꽃잎 (재료 적음)', r['tile']=='dirt,gMoss,petalR,petalW' and r['tileN']<=4, str(r))
        rec('꾸미기','나무·덤불: 흙·이끼', r['tree']=='dirt,gMoss' and r['shrub']=='dirt,gMoss', str(r))
        rec('꾸미기','꽃밭: 흙·이끼·빨·파·노 꽃잎', r['bed']=='dirt,gMoss,petalB,petalR,petalY', str(r))
        rec('꾸미기','물 타일 여러 종류', r['water']>=5, str(r))
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.fzones=[];['cherryTree','flowerBed','waterPond','floorCherry'].forEach(i=>__T.addItem(i,4));const put=(id,x,y)=>{G.sel=G.inv.findIndex(s=>s&&s.id===id);G.p.x=x-1+.5;G.p.y=y+.5;G.p.face={x:1,y:0};const d=__T.decide();__T.perform(d);return d.k};return [put('cherryTree',108,108),put('flowerBed',108,111),put('waterPond',108,114),put('floorCherry',108,116)]}")
        rec('꾸미기','벚꽃나무·꽃밭·물 타일·벚꽃 타일 설치', r==['place']*4, str(r))
        r=await ev(pg,"()=>[__T.isSolid(108,108),__T.isSolid(108,111),__T.isSolid(108,114),__T.G.floor[__T.idx(108,114)],__T.G.floor[__T.idx(108,116)]]")
        rec('꾸미기','벚꽃나무는 막히고 꽃밭·물 타일은 지나갈 수 있음', r[:3]==[True,False,False] and r[3]==12 and r[4]==16, str(r))
        r=await ev(pg,"()=>{const G=__T.G;__T.addItem('shovel',1);G.sel=G.inv.findIndex(s=>s&&s.id==='shovel');G.p.x=107.5;G.p.y=114.5;G.p.face={x:1,y:0};const d=__T.decide();__T.perform(d);return [d.lbl,G.floor[__T.idx(108,114)],__T.countItem('waterPond')]}")
        rec('꾸미기','물 타일도 삽으로 걷어 회수', r[0]=='걷기' and r[1]==1 and r[2]==4, str(r))
        await pg.wait_for_timeout(300); await ev(pg,"()=>{__T.G.p.x=105.5;__T.G.p.y=113.5}")
        await ev(pg,"""()=>{const G=__T.G;const put=(t,x,y)=>G.objs.set(__T.idx(x,y),{t});put('cherryTree',103,108);put('roundTree',100,110);put('shrub',101,112);put('hydrangea',102,112);put('roseBlack',103,112);put('sunflower',104,110);put('daisies',99,113);put('flowerBed',100,113);
          for(let y=114;y<=116;y++)for(let x=99;x<=103;x++)G.floor[__T.idx(x,y)]=[11,12,13,14,15][(x+y)%5];for(let x=104;x<=107;x++)G.floor[__T.idx(x,114)]=16;G.objs.set(__T.idx(106,108),{t:'sapling',at:G.time+170});G.objs.set(__T.idx(107,108),{t:'sapling',at:G.time+60});G.objs.set(__T.idx(108,108),{t:'stump',g:'root',at:G.time+99});
          for(const c of ['R','B','Y','W','K']){const e=__T.mkEnemy('bloom'+c,98+ 'RBYWK'.indexOf(c)*1.6,106.5);G.enemies.push(e)}}""")
        await ev(pg,"()=>{const G=__T.G;for(let x=99;x<=103;x++){G.floor[__T.idx(x,117)]=__T.WATER;G.floor[__T.idx(x,118)]=[11,16,5,12,15][x-99]}G.floor[__T.idx(104,116)]=__T.WATER}")
        await pg.wait_for_timeout(900); await pg.screenshot(path=SP+'qa18_garden.png')
        rec('꾸미기','물 타일·벚꽃 타일을 진짜 물 옆에 깔아도 화면 오류 없음', not errs, errs[:2])
        rec('기능','콘솔 오류 없음 (기능)', not errs, errs[:3]); await ctx.close()
        # ---------- drag & drop ----------
        for touch in [False, True]:
            ctx,pg,errs=await new_ctx(b,390 if touch else 1280,844 if touch else 800,touch)
            await ev(pg,"()=>{const G=__T.G;for(let i=0;i<30;i++)G.inv[i]=null;G.inv[0]={id:'wood',c:5};G.inv[1]={id:'stone',c:3};G.inv[8]={id:'wood',c:90};G.inv[12]={id:'gel',c:2};__T.refreshHotbar()}")
            await pg.wait_for_timeout(300)
            async def drag(a,b2,steps=8,hold=0):
                await pg.evaluate("([a,b])=>{const B=document.querySelector(b);if(B&&B.closest('.sh-body'))B.scrollIntoView({block:'center'});}",[a,b2]); await pg.wait_for_timeout(100)
                ra=await pg.locator(a).bounding_box(); rb=await pg.locator(b2).bounding_box()
                x0,y0=ra['x']+ra['width']/2,ra['y']+ra['height']/2; x1,y1=rb['x']+rb['width']/2,rb['y']+rb['height']/2
                kind='touch' if touch else 'mouse'
                await pg.dispatch_event(a,'pointerdown',{'pointerId':5,'pointerType':kind,'isPrimary':True,'clientX':x0,'clientY':y0,'button':0,'bubbles':True})
                if hold: await pg.wait_for_timeout(hold)
                for k in range(1,steps+1):
                    await pg.evaluate("([x,y,k])=>window.dispatchEvent(new PointerEvent('pointermove',{pointerId:5,pointerType:k,clientX:x,clientY:y,bubbles:true}))",[x0+(x1-x0)*k/steps,y0+(y1-y0)*k/steps,kind]); await pg.wait_for_timeout(16)
                await pg.evaluate("([x,y,k])=>window.dispatchEvent(new PointerEvent('pointerup',{pointerId:5,pointerType:k,clientX:x,clientY:y,bubbles:true}))",[x1,y1,kind])
                await pg.evaluate("([x,y])=>{const el=document.elementFromPoint(x,y);if(el)el.click()}",[x1,y1]); await pg.wait_for_timeout(250)
            nm='모바일' if touch else 'PC'
            await drag('#hotbar [data-i="0"]','#hotbar [data-i="3"]', hold=300 if touch else 0)
            r=await ev(pg,"()=>[__T.G.inv[0],__T.G.inv[3]&&__T.G.inv[3].id,__T.G.sel]")
            rec('드래그',f'{nm} 단축칸끼리 끌어서 옮기기', r[0] is None and r[1]=='wood', str(r))
            await pg.tap('#bInv') if touch else await pg.click('#bInv'); await pg.wait_for_timeout(600)
            await drag('#sheet [data-a=inv][data-i="12"]','#sheet [data-a=inv][data-i="2"]', hold=300 if touch else 0)
            r=await ev(pg,"()=>[__T.G.inv[12],__T.G.inv[2]&&__T.G.inv[2].id,document.querySelector('.detail')?1:0]")
            rec('드래그',f'{nm} 가방 → 단축칸 끌어 놓기', r[0] is None and r[1]=='gel', str(r))
            rec('드래그',f'{nm} 끌고 난 뒤 칸이 선택되지 않음', r[2]==0, str(r))
            await drag('#sheet [data-a=inv][data-i="3"]','#sheet [data-a=inv][data-i="8"]', hold=300 if touch else 0)
            r=await ev(pg,"()=>[__T.G.inv[3],__T.G.inv[8]&&__T.G.inv[8].c]")
            rec('드래그',f'{nm} 같은 물건 위에 놓으면 합쳐짐', r[0] is None and r[1]==95, str(r))
            await drag('#sheet [data-a=inv][data-i="1"]','#sheet [data-a=inv][data-i="1"]')
            r=await ev(pg,"()=>__T.G.inv[1]&&__T.G.inv[1].id"); rec('드래그',f'{nm} 제자리에 놓으면 그대로', r=='stone', r)
            if touch:
                await ev(pg,"()=>{__T.closePanel();__T.openPanel('inv')}"); await pg.wait_for_timeout(500)
                await drag('#sheet [data-a=inv][data-i="20"]','#sheet [data-a=inv][data-i="14"]',steps=6)
                r=await ev(pg,"()=>[__T.G.inv[20],__T.G.inv[14],document.querySelector('.sh-body').scrollTop]")
                rec('드래그','모바일 빈 칸에서 위아래로 밀어도 오류 없음', True, str(r))
                await ev(pg,"()=>{__T.G.inv[26]={id:'dirt',c:4};__T.refreshHotbar()}"); await pg.wait_for_timeout(200)
                await drag('#sheet [data-a=inv][data-i="26"]','#sheet [data-a=inv][data-i="14"]',steps=6)
                r=await ev(pg,"()=>[__T.G.inv[26]&&__T.G.inv[26].id,__T.G.inv[14]]")
                rec('드래그','모바일 빠르게 위로 밀면 옮기지 않고 스크롤', r[0]=='dirt' and r[1] is None, str(r))
            await ev(pg,"()=>__T.closePanel()")
            # chest
            await ev(pg,"()=>{const G=__T.G;const i=__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1);G.objs.set(i,{t:'chest',items:Array(18).fill(null)});G.objs.get(i).items[0]={id:'crystal',c:7};__T.openPanel('chest',{i})}")
            await pg.wait_for_timeout(600)
            await drag('#sheet [data-a=cout][data-i="0"]','#sheet [data-a=cin][data-i="15"]', hold=300 if touch else 0)
            r=await ev(pg,"()=>{const G=__T.G,o=G.objs.get(__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1));return [o.items[0],G.inv[15]&&G.inv[15].id]}")
            rec('드래그',f'{nm} 상자 → 가방 원하는 칸', r[0] is None and r[1]=='crystal', str(r))
            await drag('#sheet [data-a=cin][data-i="2"]','#sheet [data-a=cout][data-i="5"]', hold=300 if touch else 0)
            r=await ev(pg,"()=>{const G=__T.G,o=G.objs.get(__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1));return [o.items[5]&&o.items[5].id,G.inv[2]]}")
            rec('드래그',f'{nm} 가방 → 상자 원하는 칸', r[0]=='gel' and r[1] is None, str(r))
            r=await ev(pg,"()=>{let n=0;const seen=new Set();const G=__T.G,o=G.objs.get(__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1));for(const s of [...G.inv,...o.items])if(s){n+=s.c}return n}")
            rec('드래그',f'{nm} 옮기는 동안 개수가 줄거나 늘지 않음', r==5+3+90+2+7+(4 if touch else 0), r)
            r=await ev(pg,"()=>!document.querySelector('#dragGhost')"); rec('드래그',f'{nm} 끌기 표시가 남지 않음', r, r)
            rec('기능',f'{nm} 드래그 콘솔 오류 없음', not errs, errs[:3]); await ctx.close()
        # ---------- mobile button layout ----------
        for (w,h,name) in [(390,844,'iPhone 14'),(360,640,'small Android'),(375,667,'iPhone SE'),(430,932,'Pro Max'),(844,390,'landscape')]:
            ctx,pg,errs=await new_ctx(b,w,h,True)
            await ev(pg,"()=>{document.body.classList.add('touch');const G=__T.G;G.rpg.sk.dash=1;G.rpg.slot=['dash',null];G.objs.set(__T.idx(Math.floor(G.p.x),Math.floor(G.p.y)+1),{t:'chair'});G.p.face={x:0,y:1};for(let k=0;k<3;k++)window.__toast&&0}")
            await pg.wait_for_timeout(500)
            r=await ev(pg,"""()=>{const q=s=>{const e=document.querySelector(s);if(!e)return null;const cs=getComputedStyle(e);if(e.hidden||cs.display==='none')return null;const r=e.getBoundingClientRect();return r.width?{x:r.left,y:r.top,r:r.right,b:r.bottom}:null};
              const E={craft:q('#bCraft'),stat:q('#bStat'),map:q('#bMap'),menu:q('#bMenu'),act:q('#actBtn'),sub:q('#subBtn'),sk:q('#skBar'),hot:q('#hotbar'),bars:q('#hud .bars'),joy:q('#joy')};const ov=(a,b)=>a&&b&&a.x<b.r-1&&b.x<a.r-1&&a.y<b.b-1&&b.y<a.b-1;
              const bad=[];const ks=Object.keys(E);for(let a=0;a<ks.length;a++)for(let b=a+1;b<ks.length;b++)if(ov(E[ks[a]],E[ks[b]]))bad.push(ks[a]+'/'+ks[b]);
              const out=ks.filter(k=>E[k]&&k!=='joy'&&(E[k].x<0||E[k].y<0||E[k].r>innerWidth+1||E[k].b>innerHeight+1));
              return {bad,out,low:E.craft?[0,Math.round(E.craft.y),Math.round(E.sub.y),Math.round(E.act.y)]:null,right:E.craft?innerWidth-E.craft.r:null}}""")
            land = w>h
            rec('레이아웃',f'{name} 버튼 겹침 없음', not r['bad'] and not r['out'], str(r))
            if not land: rec('레이아웃',f'{name} 가방·제작이 우측 하단(상호작용 버튼 위)', r['low'][0]<r['low'][1]<r['low'][2]<r['low'][3] and r['low'][1]>h*0.4 and r['right']<30, str(r))
            await pg.screenshot(path=SP+f'qa18_layout_{w}x{h}.png')
            await pg.tap('#bCraft'); await pg.wait_for_timeout(500)
            r=await ev(pg,"()=>!!document.querySelector('#sheetWrap:not([hidden]) .sh-head')"); rec('레이아웃',f'{name} 옮긴 제작 버튼 동작', r, r)
            if name=='iPhone 14':
                await ev(pg,"()=>{__T.closePanel();__T.openPanel('craft',{st:'bench'})}"); await pg.wait_for_timeout(500); await pg.tap('[data-a=tab][data-i=nature]'); await pg.wait_for_timeout(300); await pg.screenshot(path=SP+'qa18_nature_tab.png')
            await ev(pg,"()=>__T.closePanel()"); await pg.tap('#bInv'); await pg.wait_for_timeout(500)
            r=await ev(pg,"()=>document.querySelector('.sh-head h2').textContent"); rec('레이아웃',f'{name} 옮긴 가방 버튼 동작', '가방' in r, r)
            rec('기능',f'{name} 콘솔 오류 없음', not errs, errs[:3]); await ctx.close()
        # ---------- save ----------
        ctx,pg,errs=await new_ctx(b,390,844,True)
        r=await ev(pg,"()=>{const G=__T.G;G.regen=[[__T.idx(110,110),'grass',G.time+50,null]];G.fzones[0].dead=[G.time+30];const s=JSON.parse(JSON.stringify(__T.serialize()));const z=JSON.stringify(G.fzones.map(z=>[z.x,z.y,z.c]));__T.deserialize(s);return [JSON.stringify(G.fzones.map(z=>[z.x,z.y,z.c]))===z,__T.G.fzones[0].dead.length,__T.G.regen.length]}")
        rec('저장','꽃망울 구역·리젠 대기가 저장됨', r==[True,1,1], str(r))
        r=await ev(pg,"()=>{const s=__T.serialize();delete s.fzones;delete s.regen;__T.deserialize(s);return [__T.G.fzones.length,__T.G.regen.length]}")
        rec('저장','예전 세이브도 구역이 생김', r[0]>=8 and r[1]==0, str(r))
        rec('기능','콘솔 오류 없음 (저장)', not errs, errs[:3]); await ctx.close()
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
