import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,RECIPES,checkGuide,circuitTick,isSolid,perform,decide,GUIDE,QSIDE,wirePowered,refreshHotbar}")
ARENA="()=>{const G=__T.G;for(let y=100;y<120;y++)for(let x=100;x<124;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=1}G.wire=new Map();G.enemies.length=0;G.p.x=101.5;G.p.y=118.5;G.p.face={x:1,y:0}}"
W="(xs,y)=>xs.forEach(x=>__T.G.wire.set(__T.idx(x,y),1))"
O="(t,x,y,ex)=>{const o=Object.assign({t},ex||{});__T.G.objs.set(__T.idx(x,y),o);return o}"
TICK="(n,dt)=>{for(let k=0;k<n;k++)__T.circuitTick(dt||.2)}"
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch(); ctx,pg,errs=await new_ctx(b,390,844,True)
        await ev(pg,f"()=>{{window.W={W};window.O={O};window.TK={TICK}}}")
        # ---------- quests ----------
        r=await ev(pg,"()=>{const R=__T.RECIPES.find(r=>r.out==='gMoss');return [R.at,JSON.stringify(R.req)]}")
        rec('이끼','이끼 섬유 3개로 이끼 한 삽 (손 제작)', r==[None,'[["fiber",1]]'], str(r))
        await pg.tap('#goal'); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>[document.querySelector('.sh-head h2').textContent,[...document.querySelectorAll('.qrow .st')].map(e=>e.textContent).join(','),document.querySelectorAll('.qrow h4')[1]&&document.querySelectorAll('.qrow h4')[1].textContent]")
        rec('퀘스트','지금 할 일을 누르면 퀘스트 창 · 진행 중/잠김(???) 표시', '퀘스트' in r[0] and r[1].startswith('진행 중') and r[2]=='???', str(r))
        await ev(pg,"()=>__T.closePanel()")
        r=await ev(pg,"()=>{const G=__T.G;G.stats.wood=6;__T.checkGuide();return document.querySelector('#goal').classList.contains('dot')}")
        await pg.wait_for_timeout(700); r=await ev(pg,"()=>document.querySelector('#goal').classList.contains('dot')"); rec('퀘스트','받을 보상이 있으면 지금 할 일에 점', r, r)
        await pg.tap('#bQuest'); await pg.wait_for_timeout(600)
        r=await ev(pg,"()=>{const row=document.querySelector('.qrow');return [row.querySelector('.st').textContent,!!row.querySelector('[data-a=qClaim]'),row.querySelector('.qrw').textContent]}")
        rec('퀘스트','완료 + 보상 표시 + 보상 받기 버튼', r[0]=='완료' and r[1] and '이끼 섬유 5' in r[2] and '경험치 10' in r[2], str(r))
        f0=await ev(pg,"()=>__T.countItem('fiber')")
        await pg.tap('.qrow [data-a=qClaim]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.countItem('fiber'),document.querySelector('.qrow .got')&&document.querySelector('.qrow .got').textContent,!!__T.G.qclaim.wood]")
        rec('퀘스트','보상 받으면 아이템 지급 + 받음 ✓', r[0]==f0+5 and r[1]=='받음 ✓' and r[2], str(r))
        await pg.screenshot(path=SP+'qa22_quest.png')
        await pg.tap('[data-a=qTab][data-i=side]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>document.querySelectorAll('.qrow').length"); rec('퀘스트','도전 탭에 부가 퀘스트 목록', r>=8, r)
        await ev(pg,"()=>{__T.G.stats.made={gMoss:1};__T.closePanel();__T.openPanel('quest');}"); await pg.wait_for_timeout(500); await pg.tap('[data-a=qTab][data-i=side]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>{const row=document.querySelector('.qrow');return [row.querySelector('h4').textContent,!!row.querySelector('[data-a=qClaim]')]}")
        rec('퀘스트','완료한 도전이 맨 위에 + 보상 받기', '이끼 한 삽' in r[0] and r[1], str(r))
        await pg.tap('[data-a=qClaimAll]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>{const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);return [!!__T.G.qclaim.s_moss,!!__T.G.qclaim.wood]}")
        rec('퀘스트','받은 기록이 저장됨', r==[True,True], str(r)); await ev(pg,"()=>__T.closePanel()")
        # ---------- circuits ----------
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{O('battery',102,105,{e:600});W([103,104,105,106],105);const L=O('eLamp',107,105,{off:true});TK(2);return [L.off,__T.wirePowered(__T.idx(104,105)),!!__T.G.stats.litLamp]}")
        rec('회로','건전지 → 전선 → 전기 램프가 켜짐', r==[False,True,True], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.wire.delete(__T.idx(105,105));const L=G.objs.get(__T.idx(107,105));TK(2);return [L.off,__T.wirePowered(__T.idx(106,105))]}")
        rec('회로','전선이 끊기면 꺼짐', r==[True,False], str(r))
        r=await ev(pg,"()=>{const lv=O('lever',105,105);const L=__T.G.objs.get(__T.idx(107,105));TK(2);const a=L.off;lv.on=true;TK(2);const b=L.off;return [a,b]}")
        rec('회로','레버: 꺼져 있으면 끊고 켜면 이어 줌', r==[True,False], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(105,105));O('plate',105,105);const L=G.objs.get(__T.idx(107,105));G.p.x=101.5;G.p.y=118.5;TK(2);const a=L.off;G.p.x=105.5;G.p.y=105.5;TK(2);const b=L.off;G.p.x=101.5;G.p.y=118.5;return [a,b]}")
        rec('회로','압력판: 올라서 있는 동안만 켜짐', r==[True,False], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(105,105));O('timer',105,105,{per:1});const L=G.objs.get(__T.idx(107,105));const seen=new Set();for(let k=0;k<20;k++){TK(1,.2);seen.add(L.off)}return seen.size}")
        rec('회로','타이머: 켜졌다 꺼졌다 반복', r==2, r)
        # door
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(105,105));G.wire.set(__T.idx(105,105),1);G.objs.delete(__T.idx(107,105));const D=O('eDoor',107,105);TK(2);const a=[D.open,__T.isSolid(107,105)];G.wire.delete(__T.idx(105,105));TK(2);return [a,[!!D.open,__T.isSolid(107,105)]]}")
        rec('회로','전기 문: 전기 들어오면 열리고 끊기면 닫힘', r==[[True,False],[False,True]], str(r))
        # drill + chest + battery drain
        await ev(pg,ARENA)
        r=await ev(pg,"()=>{const G=__T.G;G.wall[__T.idx(110,104)]=4;O('battery',108,108,{e:600});W([109],108);W([110],108);const Dr=O('drillCu',110,105,{dir:{x:0,y:-1}});W([110,111],106);W([110],107);const C=O('chest',111,105,{items:Array(18).fill(null)});TK(65,.2);return [C.items.filter(Boolean).map(s=>s.id+':'+s.c).join(','),G.wall[__T.idx(110,104)],Math.round(G.objs.get(__T.idx(108,108)).e)]}")
        rec('채굴기','구리 광맥 앞 채굴기가 12초마다 광석을 옆 상자에 담음', r[0]=='copperOre:1' and r[1]==4 and r[2]<600, str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(111,105));TK(130,.2);const Dr=G.objs.get(__T.idx(110,105));return [(Dr.store||[]).map(s=>s.id+':'+s.c).join(','),__T.G.stats.drilled]}")
        rec('채굴기','상자가 없으면 채굴기 안에 모아 둠', r[0].startswith('copperOre:') and r[1]>=2, str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.p.x=110.5;G.p.y=106.5;G.p.face={x:0,y:-1};const d=__T.decide();const before=__T.countItem('copperOre');__T.perform(d);return [d.k,d.lbl,__T.countItem('copperOre')-before]}")
        rec('채굴기','채굴기를 누르면 꺼내기', r[0]=='use' and r[1]=='꺼내기' and r[2]>=2, str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.wall[__T.idx(110,104)]=3;TK(3);const Dr=G.objs.get(__T.idx(110,105));return [Dr.work,Dr.why]}")
        rec('채굴기','구리 채굴기는 수정벽을 못 캠', r==[False,'tier'], str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.wall[__T.idx(110,104)]=4;const B=G.objs.get(__T.idx(108,108));B.e=1;TK(20,.2);const Dr=G.objs.get(__T.idx(110,105));return [Math.round(B.e),Dr.work,Dr.why]}")
        rec('건전지','건전지가 다 닳으면 멈춤', r==[0,False,'power'], str(r))
        # generator
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(108,108));const g=O('generator',108,108);__T.addItem('wood',5);G.p.x=108.5;G.p.y=109.5;G.p.face={x:0,y:-1};const d=__T.decide();__T.perform(d);const f0=g.fuel;TK(10,.2);const Dr=G.objs.get(__T.idx(110,105));return [d.lbl,f0,Math.round(g.fuel),Dr.work,!!G.stats.genRun,__T.countItem('wood')]}")
        rec('발전기','연료 넣기 → 전기 공급, 일할 때만 연료 사용', r[0]=='연료 넣기' and r[1]==150 and r[2]==148 and r[3] and r[4] and r[5]==0, str(r))
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(108,108));O('crystalGen',108,108);TK(5);return G.objs.get(__T.idx(110,105)).work}")
        rec('발전기','수정 발전기는 연료 없이 작동', r, r)
        # battery pickup keeps charge, recharge with repair
        r=await ev(pg,"()=>{const G=__T.G;G.objs.delete(__T.idx(108,108));O('battery',108,108,{e:123});G.p.x=108.5;G.p.y=109.5;G.p.face={x:0,y:-1};__T.perform({k:'pickup',t:{x:108,y:108},o:G.objs.get(__T.idx(108,108))});const s=G.inv.find(s=>s&&s.id==='battery');return [s&&s.dur,!!G.objs.get(__T.idx(108,108))]}")
        rec('건전지','회수해도 남은 전기가 유지됨', r==[123,False], str(r))
        r=await ev(pg,"()=>{const G=__T.G;const k=G.inv.findIndex(s=>s&&s.id==='battery');const tmp=G.inv[0];G.inv[0]=G.inv[k];G.inv[k]=tmp;G.sel=0;const d=__T.decide();__T.perform(d);const o=G.objs.get(__T.idx(108,108));return [d.k,o&&o.t,o&&o.e]}")
        rec('건전지','다시 놓으면 그 전기 그대로', r==['place','battery',123], str(r))
        # wires: place & pick up with the wire item
        r=await ev(pg,"()=>{const G=__T.G;for(let i=0;i<9;i++)G.inv[i]=null;G.inv[0]={id:'wire',c:5};G.sel=0;G.p.x=114.5;G.p.y=112.5;G.p.face={x:1,y:0};const d1=__T.decide();__T.perform(d1);const a=G.wire.has(__T.idx(115,112));const d2=__T.decide();__T.perform(d2);return [d1.lbl,a,d2.lbl,G.wire.has(__T.idx(115,112)),__T.countItem('wire')]}")
        rec('전선','전선 깔기 / 같은 칸에서 전선 걷기', r==['전선 깔기',True,'전선 걷기',False,5], str(r))
        r=await ev(pg,"()=>{W([120,121],110);const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);return [__T.G.wire.size>=3,__T.G.objs.get(__T.idx(110,105)).dir.y]}")
        rec('저장','전선·기계 상태가 저장됨', r==[True,-1], str(r))
        r=await ev(pg,"()=>__T.RECIPES.filter(r=>r.cat==='circuit').map(r=>r.out+'@'+r.at).join(',')")
        rec('제작','회로 탭 레시피 (구리 제작대, v46: 벽 앞 채굴기는 채굴장으로 바뀌어 빠짐)', all(x in r for x in ['wire@forge','battery@forge','generator@forge','crystalGen@forge']) and 'drillCu@forge' not in r, r)
        # visual
        await ev(pg,ARENA)
        await ev(pg,"()=>{const G=__T.G;G.treeSeeds=3;O('battery',103,113,{e:400});W([104,105],113);O('lever',106,113,{on:true});W([107,108,109],113);O('eLamp',110,113,{off:true});W([109],112);W([109],111);O('eDoor',109,110);W([104],114);W([104],115);O('plate',105,115);W([106,107],115);O('eLamp',108,115,{off:true});G.wall[__T.idx(113,111)]=5;O('drillCu',113,112,{dir:{x:0,y:-1}});W([111,112],113);W([113],113);O('chest',114,112,{items:Array(18).fill(null)});G.p.x=107.5;G.p.y=117.5;TK(3)}")
        await pg.wait_for_timeout(1200); await pg.screenshot(path=SP+'qa22_circuit.png')
        rec('기능','콘솔 오류 없음', not errs, errs[:3]); await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
