import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,RECIPES,decide,perform,growTick,refreshHotbar,canCraft:typeof canCraft!=='undefined'?canCraft:null,nearStations,stashBag,placeItem,hitObj}")
ARENA="()=>{const G=__T.G;for(let y=100;y<114;y++)for(let x=100;x<116;x++){const i=__T.idx(x,y);G.wall[i]=0;G.objs.delete(i);G.floor[i]=1}G.enemies.length=0;G.p.x=104.5;G.p.y=106.5;G.p.face={x:1,y:0};for(let i=0;i<G.inv.length;i++)G.inv[i]=null;G.sel=0}"
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch(); ctx,pg,errs=await new_ctx(b,390,844,True)
        await ev(pg,ARENA)
        # trees
        r=await ev(pg,"""()=>{const T=__T,G=T.G;const i=T.idx(105,106);G.objs.set(i,{t:'cherryTree'});G.inv[0]={id:'shovel',c:1};G.sel=0;const a=T.decide();
          G.inv[0]={id:'pickIron',c:1};for(let k=0;k<12&&G.objs.get(i)&&G.objs.get(i).t==='cherryTree';k++)T.hitObj({x:105,y:106},G.objs.get(i));const o=G.objs.get(i);return [a.k,o&&o.t,o&&o.g,G.drops.some(d=>d.id==='wood')]}""")
        rec('나무','다 자란 벚꽃나무는 삽으로 못 퍼고(안내) 베어야 함 → 그루터기', r[0]=='info' and r[1]=='stump' and r[2]=='cherryTree' and r[3], str(r))
        r=await ev(pg,"""()=>{const T=__T,G=T.G;const i=T.idx(105,106);G.inv[0]={id:'shovel',c:1};G.sel=0;const a=T.decide();T.perform(a);return [a.k,G.objs.get(i)||null,T.countItem('cherryTree')]}""")
        rec('나무','그루터기는 삽으로 뽑히고 나무 아이템으로 돌아옴', r[0]=='dig' and r[1] is None and r[2]==1, str(r))
        r=await ev(pg,"""()=>{const T=__T,G=T.G;const i=T.idx(105,106);G.objs.set(i,{t:'stump',g:'roundTree',at:G.time-1});G.p.x=102.5;T.growTick();const t=G.objs.get(i).t;G.p.x=104.5;return t}""")
        rec('나무','그루터기는 시간이 지나면 원래 나무로 다시 자람', r=='roundTree', r)
        r=await ev(pg,"""()=>{const T=__T,G=T.G;const i=T.idx(105,106);G.objs.set(i,{t:'sapling',at:G.time-1});G.p.x=102.5;T.growTick();const o=G.objs.get(i);G.inv[0]={id:'pickIron',c:1};for(let k=0;k<12&&G.objs.get(i)&&G.objs.get(i).t==='root';k++)T.hitObj({x:105,y:106},G.objs.get(i));G.p.x=104.5;return [o.t,G.objs.get(i)&&G.objs.get(i).t]}""")
        rec('나무','직접 심은 묘목이 자란 뿌리기둥도 베면 그루터기', r==['root','stump'], str(r))
        # chest stash
        r=await ev(pg,"""()=>{const T=__T,G=T.G;for(let i=0;i<G.inv.length;i++)G.inv[i]=null;G.inv[0]={id:'torch',c:5};G.inv[9]={id:'stone',c:30};G.inv[10]={id:'wood',c:20};G.inv[11]={id:'swordWood',c:1};const ci=T.idx(106,106);const o={t:'chest',items:Array(18).fill(null)};o.items[0]={id:'stone',c:10};G.objs.set(ci,o);G.p.x=104.5;G.p.y=106.5;T.openPanel('chest',{i:ci});return true}""")
        await pg.wait_for_timeout(600)
        await pg.tap('[data-a=stash][data-i=same]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>{const T=__T,G=T.G,o=G.objs.get(T.idx(106,106));return [o.items[0].c,T.countItem('wood'),T.countItem('torch')]}")
        rec('상자','같은 것만 넣기: 상자에 있는 돌만 들어감', r==[40,20,5], str(r))
        await pg.screenshot(path=SP+'qa25_chest.png')
        await pg.tap('[data-a=stash][data-i=all]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>{const T=__T,G=T.G,o=G.objs.get(T.idx(106,106));return [T.countItem('wood'),T.countItem('swordWood'),T.countItem('torch'),o.items.filter(Boolean).length]}")
        rec('상자','모두 넣기: 가방 물건은 다 들어가고 단축칸은 그대로', r==[0,0,5,3], str(r))
        r=await ev(pg,"()=>{const T=__T,G=T.G,o=G.objs.get(T.idx(106,106));for(let k=0;k<18;k++)o.items[k]={id:'dirt',c:999};G.inv[12]={id:'wood',c:7};return T.stashBag(o,false)}")
        rec('상자','상자가 가득 차면 남은 건 가방에', r['n']==0 and r['left']==1, str(r))
        await ev(pg,"()=>__T.closePanel()")
        # crafting per station
        await ev(pg,ARENA)
        await ev(pg,"()=>{const T=__T,G=T.G;G.objs.set(T.idx(106,105),{t:'bench'});G.objs.set(T.idx(106,107),{t:'pot'});G.objs.set(T.idx(103,105),{t:'forge'});for(const[id,c]of[['wood',99],['fiber',99],['copperBar',40],['resin',20],['dirt',40],['stone',40],['rope',20],['gel',20],['mushroom',20],['berry',20]])T.addItem(id,c,false)}")
        await ev(pg,"()=>__T.openPanel('craft')"); await pg.wait_for_timeout(500)
        r=await ev(pg,"""()=>{const T=__T;const ats=new Set();document.querySelectorAll('#sheet .rc [data-a=craft]').forEach(b=>ats.add(T.RECIPES[+b.dataset.i].at||'hand'));const ok=[...document.querySelectorAll('#sheet .rc [data-a=craft]:not([disabled])')].map(b=>T.RECIPES[+b.dataset.i].at||'hand');return [[...ats].join(','),[...new Set(ok)].join(','),[...document.querySelectorAll('#sheet .tab')].map(t=>t.textContent).join(',')]}""")
        rec('제작','손 제작 창에는 손 제작만 (작업대·솥·구리 제작대가 근처여도)', r[0]=='hand' and r[1]=='hand' and '수리' not in r[2], str(r))
        await ev(pg,"()=>__T.closePanel()"); await pg.wait_for_timeout(300)
        for st in ['bench','pot','forge']:
            await ev(pg,f"()=>__T.openPanel('craft',{{st:'{st}'}})"); await pg.wait_for_timeout(450)
            r=await ev(pg,"""()=>{const T=__T;const ats=new Set();document.querySelectorAll('#sheet .rc [data-a=craft]').forEach(b=>ats.add(T.RECIPES[+b.dataset.i].at||'hand'));return [[...ats].join(','),document.querySelectorAll('#sheet .rc [data-a=craft]:not([disabled])').length,[...document.querySelectorAll('#sheet .tab')].map(t=>t.textContent).join(',')]}""")
            rec('제작',f'{st} 창에는 {st} 제작품만', r[0]==st and r[1]>0, str(r))
            if st=='bench': await pg.screenshot(path=SP+'qa25_bench.png')
            await ev(pg,"()=>__T.closePanel()"); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>{const R=__T.RECIPES.find(r=>r.out==='gMoss');return JSON.stringify(R.req)+R.at}")
        rec('제작','이끼 한 삽 = 이끼 섬유 1개 (손 제작)', r=='[["fiber",1]]null', r)
        # moss meadow
        r=await ev(pg,"""()=>{const T=__T,G=T.G;for(let i=0;i<G.inv.length;i++)G.inv[i]=null;G.inv[0]={id:'meadow',c:4};G.sel=0;G.p.x=104.5;G.p.y=106.5;G.p.face={x:1,y:0};const i=T.idx(105,106);G.objs.delete(i);let a=T.decide();T.perform(a);const f=G.floor[i];
          G.inv[1]={id:'mossSpore',c:3};G.sel=1;a=T.decide();T.perform(a);const o=G.objs.get(i);
          G.sel=1;G.floor[T.idx(105,107)]=1;return [f,o&&o.t,a.k]}""")
        rec('이끼밭','풀밭 깔고 이끼 포자 심기', r[0]==21 and r[1]=='cropMoss', str(r))
        r=await ev(pg,"""()=>{const T=__T,G=T.G;const i=T.idx(105,106);G.objs.get(i).p=G.time-200;const a=T.decide();G.drops.length=0;T.perform(a);return [a.k,G.drops.map(d=>d.id).sort().join(','),G.floor[i]]}""")
        rec('이끼밭','다 자라면 수확: 이끼 한 삽 + 포자, 풀밭은 그대로', r[0]=='harvest' and 'gMoss' in r[1] and 'mossSpore' in r[1] and r[2]==21, str(r))
        r=await ev(pg,"""()=>{const T=__T,G=T.G;G.p.y=107.5;G.p.face={x:1,y:0};const i=T.idx(105,107);G.objs.delete(i);G.floor[i]=1;G.sel=1;return T.decide().k}""")
        rec('이끼밭','이끼 포자는 풀밭이 아닌 곳엔 못 심음', r!='place', r)
        # d-pad
        await ev(pg,"()=>{__T.openPanel('menu')}"); await pg.wait_for_timeout(500)
        await pg.tap('[data-a=ctrl][data-i=pad]'); await pg.wait_for_timeout(200)
        await ev(pg,"()=>__T.closePanel()"); await pg.wait_for_timeout(400)
        r=await ev(pg,"()=>[document.body.classList.contains('padmode'),getComputedStyle(document.querySelector('#dpad')).display,localStorage.getItem('lantern-tree-ctrl')]")
        rec('방향키','설정에서 방향키로 바꾸면 십자 패드 표시 + 저장', r[0] and r[1]=='block' and r[2]=='pad', str(r))
        await ev(pg,ARENA)
        box=await pg.locator('#dpad').bounding_box()
        x0=await ev(pg,"()=>__T.G.p.x")
        cx,cy=box['x']+box['width']-20, box['y']+box['height']/2
        await pg.dispatch_event('#dpad','pointerdown',{'pointerId':21,'pointerType':'touch','isPrimary':True,'clientX':cx,'clientY':cy,'bubbles':True})
        await pg.wait_for_timeout(500)
        r1=await ev(pg,"()=>[document.querySelector('#dpad .r').classList.contains('on'),__T.G.p.x]")
        await pg.dispatch_event('#dpad','pointerup',{'pointerId':21,'pointerType':'touch','isPrimary':True,'clientX':cx,'clientY':cy,'bubbles':True})
        await pg.wait_for_timeout(300)
        r2=await ev(pg,"()=>__T.G.p.x")
        await pg.wait_for_timeout(300)
        r3=await ev(pg,"()=>__T.G.p.x")
        rec('방향키','오른쪽 누르면 오른쪽으로 걷고, 떼면 멈춤', r1[0] and r1[1]>x0+1 and abs(r3-r2)<0.05, f'{x0}->{r1} {r2} {r3}')
        r=await ev(pg,"()=>{const T=__T,G=T.G;G.p.x=104.5;return 1}")
        await pg.dispatch_event('#cv','pointerdown',{'pointerId':22,'pointerType':'touch','isPrimary':True,'clientX':100,'clientY':500})
        await pg.dispatch_event('#cv','pointermove',{'pointerId':22,'pointerType':'touch','isPrimary':True,'clientX':150,'clientY':500})
        await pg.wait_for_timeout(400)
        r=await ev(pg,"()=>[__T.G.p.x,document.querySelector('#joy').classList.contains('on')]")
        await pg.dispatch_event('#cv','pointerup',{'pointerId':22,'pointerType':'touch','isPrimary':True,'clientX':150,'clientY':500})
        rec('방향키','방향키 모드에선 화면 끌기 조이스틱이 안 생김', r[0] < 104.6 and not r[1], str(r))
        await pg.screenshot(path=SP+'qa25_dpad.png')
        await ev(pg,"()=>{__T.openPanel('menu')}"); await pg.wait_for_timeout(500); await pg.tap('[data-a=ctrl][data-i=joy]'); await ev(pg,"()=>__T.closePanel()"); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>[document.body.classList.contains('padmode'),getComputedStyle(document.querySelector('#dpad')).display]")
        rec('방향키','조이스틱으로 되돌리기', r==[False,'none'], str(r))
        rec('기능','콘솔 오류 없음', not errs, errs[:4])
        await ctx.close(); await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
