import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
H2=HOOK.replace("computeLight}","computeLight,RECIPES}")
async def main():
    mkpage(SRC,'qa.html',H2)
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx,pg,errs=await new_ctx(b,390,844,True)
        await ev(pg,"()=>{const G=__T.G;G.inv.fill(null);__T.addItem('wood',40);__T.addItem('stone',30);__T.addItem('mushroom',5);__T.addItem('berry',9);__T.addItem('copperBar',5);G.objs.set(__T.idx(Math.floor(G.p.x)+1,Math.floor(G.p.y)),{t:'bench'})}")
        await ev(pg,"()=>__T.openPanel('craft',{st:'bench'})"); await pg.wait_for_timeout(600)
        await ev(pg,"()=>{const b=document.querySelector('#sheet .sh-body');b.scrollTop=420}"); await pg.wait_for_timeout(100)
        top0=await ev(pg,"()=>document.querySelector('#sheet .sh-body').scrollTop")
        # click a visible enabled craft button
        idx=await ev(pg,"()=>{const b=document.querySelector('#sheet .sh-body'),r=b.getBoundingClientRect();const bt=[...b.querySelectorAll('button.mk:not([disabled])')].find(x=>{const q=x.getBoundingClientRect();return q.top>r.top&&q.bottom<r.bottom});return bt?bt.dataset.i:null}")
        await pg.wait_for_timeout(500)
        await pg.click(f'#sheet button.mk[data-i="{idx}"]'); await pg.wait_for_timeout(300)
        top1=await ev(pg,"()=>document.querySelector('#sheet .sh-body').scrollTop")
        rec('제작','만들기 눌러도 스크롤 위치 유지', top0>100 and abs(top0-top1)<2, f'{top0} → {top1} (recipe {idx})')
        # quantity: floorWood
        fi=await ev(pg,"()=>__T.RECIPES.findIndex(r=>r.out==='floorWood')")
        has=await ev(pg,f"()=>!!document.querySelector('#sheet [data-a=qty][data-i=\"{fi}:1\"]')")
        rec('수량','나무 바닥에 수량 선택', has)
        ci=await ev(pg,"()=>__T.RECIPES.findIndex(r=>r.out==='chair')")
        has2=await ev(pg,f"()=>!!document.querySelector('#sheet [data-a=qty][data-i^=\"{ci}:\"]')")
        rec('수량','의자(가구)는 수량 선택 없음', not has2)
        await pg.click(f'#sheet [data-a=qty][data-i="{fi}:1"]'); await pg.wait_for_timeout(100); await pg.click(f'#sheet [data-a=qty][data-i="{fi}:1"]'); await pg.wait_for_timeout(100)
        lbl=await ev(pg,f"()=>document.querySelector('#sheet [data-a=qty][data-i=\"{fi}:1\"]').parentElement.querySelector('b').textContent")
        w0=await ev(pg,"()=>__T.countItem('wood')"); f0=await ev(pg,"()=>__T.countItem('floorWood')")
        await pg.click(f'#sheet button.mk[data-i="{fi}"]'); await pg.wait_for_timeout(200)
        w1=await ev(pg,"()=>__T.countItem('wood')"); f1=await ev(pg,"()=>__T.countItem('floorWood')")
        rec('수량','+ 두 번 → 12개 표시, 나무 6개 써서 바닥 12개', lbl=='12개' and w0-w1==6 and f1-f0==12, f'{lbl} wood {w0}->{w1} floor {f0}->{f1}')
        await pg.click(f'#sheet [data-a=qty][data-i="{fi}:max"]'); await pg.wait_for_timeout(100)
        lbl=await ev(pg,f"()=>document.querySelector('#sheet [data-a=qty][data-i=\"{fi}:max\"]').parentElement.querySelector('b').textContent")
        rec('수량','최대 = 가진 재료만큼', lbl==f'{(w1//2)*4}개', f'{lbl} (wood {w1})')
        await pg.click(f'#sheet button.mk[data-i="{fi}"]'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[__T.countItem('wood'), __T.G.inv.filter(Boolean).length]")
        rec('수량','최대로 만들면 나무가 1개 이하로 남음', r[0]<=1, str(r))
        await ev(pg,"()=>{document.querySelector('#sheet .sh-body').scrollTop=0}"); await pg.wait_for_timeout(100)
        await pg.screenshot(path=SP+'qa8_craft.png')
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
