import asyncio, sys
sys.argv=['x']
exec(open(__import__('os').path.join(__import__('os').path.dirname(__import__('os').path.abspath(__file__)),'qa2.py')).read().split('async def main():')[0])
async def main():
    mkpage(SRC,'qa.html')
    async with async_playwright() as p:
        b=await p.chromium.launch(); errs=[]
        ctx=await b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,has_touch=True,is_mobile=True)
        pg=await ctx.new_page(); pg.on('pageerror',lambda e: errs.append(str(e)))
        await pg.goto('file://'+SP+'qa.html'); await pg.wait_for_timeout(500)
        await pg.tap('#btnNew'); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>[!document.querySelector('#charPick').hidden, document.querySelectorAll('#cpGrid .cp-card').length, document.querySelector('#cpGrid .cp-card.on').dataset.c, document.querySelector('#btnNew').offsetParent===null]")
        rec('캐릭터 선택','새 모험 → 선택 화면 (8칸, 기본 새싹)', r==[True,8,'sprout',True], str(r))
        await pg.tap('#cpGrid [data-c=pori]'); await pg.wait_for_timeout(400)
        r=await ev(pg,"()=>[document.querySelector('#cpGrid .cp-card.on').dataset.c, document.querySelector('#cpDesc').textContent]")
        rec('캐릭터 선택','카드 누르면 선택 + 설명', r==['pori','버섯 모자를 쓴 탐험가'], str(r))
        await pg.screenshot(path=SP+'qa9_picker.png')
        await pg.tap('#charBack'); await pg.wait_for_timeout(200)
        r=await ev(pg,"()=>[document.querySelector('#charPick').hidden, document.querySelector('#btnNew').offsetParent!==null]")
        rec('캐릭터 선택','뒤로 → 첫 화면', r==[True,True], str(r))
        await pg.tap('#btnNew'); await pg.wait_for_timeout(200); await pg.tap('#cpGrid [data-c=rumi]'); await pg.wait_for_timeout(100); await pg.tap('#charGo'); await pg.wait_for_timeout(700)
        r=await ev(pg,"()=>[__T.G.char, document.querySelector('#title').hidden, __T.serialize().char]")
        rec('캐릭터 선택','루미로 시작 + 세이브에 저장', r==['rumi',True,'rumi'], str(r))
        await ev(pg,"()=>{document.getElementById('toasts').style.display='none'}")
        await pg.wait_for_timeout(300); await pg.screenshot(path=SP+'qa9_game.png')
        r=await ev(pg,"()=>{const s=JSON.parse(JSON.stringify(__T.serialize()));__T.deserialize(s);const a=__T.G.char;delete s.char;__T.deserialize(s);const b=__T.G.char;s.char='rumi';__T.deserialize(s);return [a,b]}")
        rec('저장','불러오면 캐릭터 유지 / 예전 세이브는 새싹', r==['rumi','sprout'], str(r))
        await ev(pg,"()=>{document.getElementById('toasts').style.display=''}")
        await ev(pg,"()=>__T.openPanel('menu')"); await pg.wait_for_timeout(500)
        n=await ev(pg,"()=>document.querySelectorAll('#sheet .cp-card').length")
        await pg.tap('#sheet .cp-card[data-c=momo]'); await pg.wait_for_timeout(300)
        r=await ev(pg,"()=>[__T.G.char, __T.G.outfit, document.querySelector('#toasts').innerText.includes('모모로 바꿨어요'), document.querySelector('#sheet .cp-card.on').dataset.c]")
        rec('메뉴','메뉴에서 캐릭터 바꾸기', n==8 and r==['momo',0,True,'momo'], f'{n} {r}')
        await pg.screenshot(path=SP+'qa9_menu.png')
        await pg.tap('#sheet .cp-card[data-c=todak]'); await pg.wait_for_timeout(300)
        rec('메뉴','받침 있는 이름: 토닥으로', await ev(pg,"()=>document.querySelector('#toasts').innerText.includes('토닥으로 바꿨어요')"))
        await pg.tap('#sheet .cp-card[data-c=ciel]'); await pg.wait_for_timeout(300)
        rec('메뉴','ㄹ 받침 이름: 시엘로', await ev(pg,"()=>document.querySelector('#toasts').innerText.includes('시엘로 바꿨어요')"))
        # restart keeps char
        await pg.tap('#sheet [data-a=newgame]'); await pg.wait_for_timeout(200); await pg.tap('#sheet [data-a=newgame]'); await pg.wait_for_timeout(500)
        rec('메뉴','처음부터 다시 해도 캐릭터 유지', await ev(pg,"()=>__T.G.char")=='ciel')
        rec('기능','콘솔 오류 없음', not errs, errs[:3])
        await b.close()
    print('TOTAL',sum(1 for r in RES if r[2]),'/',len(RES))
asyncio.run(main())
